"""Drop unused index

Revision ID: 53dac028bb5e
Revises: febcf9a50c01
Create Date: 2026-08-16 16:54:36.519651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53dac028bb5e'
down_revision: Union[str, Sequence[str], None] = 'febcf9a50c01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pokemon_name'), table_name='pokemon')
    op.drop_index(op.f('ix_pokemon_type_1'), table_name='pokemon')
    op.drop_index(op.f('ix_pokemon_type_2'), table_name='pokemon')
    op.drop_index(op.f('ix_pce_detected_at'), table_name='pokemon_change_event')
    op.create_index(op.f('ix_pokemon_change_event_detected_at'), 'pokemon_change_event', ['detected_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pokemon_change_event_detected_at'), table_name='pokemon_change_event')
    op.create_index(op.f('ix_pce_detected_at'), 'pokemon_change_event', ['detected_at'], unique=False)
    op.create_index(op.f('ix_pokemon_type_2'), 'pokemon', ['type_2'], unique=False)
    op.create_index(op.f('ix_pokemon_type_1'), 'pokemon', ['type_1'], unique=False)
    op.create_index(op.f('ix_pokemon_name'), 'pokemon', ['name'], unique=False)
    # ### end Alembic commands ###
