"""initial schema

Revision ID: 607b04cf3969
Revises:
Create Date: 2026-08-13 23:58:09.484318

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "607b04cf3969"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pokemon",
        sa.Column("id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("species_id", sa.Integer(), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("type_1", sa.String(length=20), nullable=False),
        sa.Column("type_2", sa.String(length=20), nullable=True),
        sa.Column("hp", sa.Integer(), nullable=False),
        sa.Column("attack", sa.Integer(), nullable=False),
        sa.Column("defense", sa.Integer(), nullable=False),
        sa.Column("special_attack", sa.Integer(), nullable=False),
        sa.Column("special_defense", sa.Integer(), nullable=False),
        sa.Column("speed", sa.Integer(), nullable=False),
        sa.Column("sprite_url", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pokemon")),
    )
    op.create_index(op.f("ix_pokemon_name"), "pokemon", ["name"], unique=False)
    op.create_index(
        op.f("ix_pokemon_species_id"), "pokemon", ["species_id"], unique=False
    )
    op.create_index(op.f("ix_pokemon_type_1"), "pokemon", ["type_1"], unique=False)
    op.create_index(op.f("ix_pokemon_type_2"), "pokemon", ["type_2"], unique=False)
    op.create_table(
        "type_matchup",
        sa.Column("attacking_type", sa.String(length=20), nullable=False),
        sa.Column("defending_type", sa.String(length=20), nullable=False),
        sa.Column("multiplier", sa.Numeric(precision=3, scale=2), nullable=False),
        sa.PrimaryKeyConstraint(
            "attacking_type", "defending_type", name=op.f("pk_type_matchup")
        ),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "pokemon_change_event",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pokemon_id", sa.Integer(), nullable=False),
        sa.Column(
            "detected_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("changes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["pokemon_id"],
            ["pokemon.id"],
            name=op.f("fk_pokemon_change_event_pokemon_id_pokemon"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pokemon_change_event")),
    )
    op.create_index(
        "ix_pce_detected_at", "pokemon_change_event", ["detected_at"], unique=False
    )
    op.create_index(
        op.f("ix_pokemon_change_event_pokemon_id"),
        "pokemon_change_event",
        ["pokemon_id"],
        unique=False,
    )
    op.create_table(
        "team",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_team_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_team")),
    )
    op.create_index(op.f("ix_team_user_id"), "team", ["user_id"], unique=False)
    op.create_table(
        "team_pokemon",
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("pokemon_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["pokemon_id"],
            ["pokemon.id"],
            name=op.f("fk_team_pokemon_pokemon_id_pokemon"),
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["team.id"],
            name=op.f("fk_team_pokemon_team_id_team"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("team_id", "position", name=op.f("pk_team_pokemon")),
    )
    op.create_index(
        "ix_team_pokemon_pokemon_id", "team_pokemon", ["pokemon_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_team_pokemon_pokemon_id", table_name="team_pokemon")
    op.drop_table("team_pokemon")
    op.drop_index(op.f("ix_team_user_id"), table_name="team")
    op.drop_table("team")
    op.drop_index(
        op.f("ix_pokemon_change_event_pokemon_id"), table_name="pokemon_change_event"
    )
    op.drop_index("ix_pce_detected_at", table_name="pokemon_change_event")
    op.drop_table("pokemon_change_event")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_table("users")
    op.drop_table("type_matchup")
    op.drop_index(op.f("ix_pokemon_type_2"), table_name="pokemon")
    op.drop_index(op.f("ix_pokemon_type_1"), table_name="pokemon")
    op.drop_index(op.f("ix_pokemon_species_id"), table_name="pokemon")
    op.drop_index(op.f("ix_pokemon_name"), table_name="pokemon")
    op.drop_table("pokemon")
    # ### end Alembic commands ###
