"""type_matchup multiplier numeric to float

Revision ID: febcf9a50c01
Revises: 607b04cf3969
Create Date: 2026-08-14 13:52:43.185925

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "febcf9a50c01"
down_revision: Union[str, Sequence[str], None] = "607b04cf3969"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "type_matchup",
        "multiplier",
        existing_type=sa.NUMERIC(precision=3, scale=2),
        type_=sa.Float(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "type_matchup",
        "multiplier",
        existing_type=sa.Float(),
        type_=sa.NUMERIC(precision=3, scale=2),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
